name: Deploy

on:
  push:
    tags:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alta-golang-miniproject:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # sudo docker stop golang-miniproject-container
            # sudo docker rm golang-miniproject-container
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alta-golang-miniproject:${{ github.ref_name }}
            sudo docker run -d --network=host --restart=always -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e JWT_KEY=${{ secrets.JWT_KEY }} -e EMAIL_SENDER_NAME=${{ secrets.EMAIL_SENDER_NAME }} -e EMAIL_SMTP_HOST=${{ secrets.EMAIL_SMTP_HOST }} -e EMAIL_SMTP_PORT=${{ secrets.EMAIL_SMTP_PORT }} -e EMAIL_SMTP_EMAIL=${{ secrets.EMAIL_SMTP_EMAIL }} -e EMAIL_SMTP_PASSWORD=${{ secrets.EMAIL_SMTP_PASSWORD }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e AWS_REGION=${{ secrets.AWS_REGION }} -e ENDPOINT=${{ secrets.ENDPOINT }} -e OPENAPI_KEY=${{ secrets.OPENAPI_KEY }} -e APP_URL=${{ secrets.APP_URL }} --name golang-miniproject-container ${{ secrets.DOCKERHUB_USERNAME }}/golang-miniproject-container:${{ github.ref_name }}
